name: CI Lingvo
on:
  # Run on manual trigger
  workflow_dispatch:

  # Run on pull requests
  pull_request:
    paths-ignore:
      - '*.md'

  # Run on merge queue
  merge_group:

  # Run when pushing to main or dev branches
  push:
    branches:
      - main
      - dev*

  # Run scheduled CI flow daily
  schedule:
    - cron: '0 8 * * 0'

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: TensorFlow+Lingvo 0.13.1 (Python 3.10)
            framework: tensorflow
            python: '3.10'
            lingvo: 0.13.1
            tensorflow: 2.14.0
            tf_version: v2
            keras: 2.14.0
            tf_addons: 0.21.0

    name: Run ${{ matrix.name }} Tests
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Pre-install Lingvo ASR
        run: |
          sudo apt-get update
          sudo apt-get -y -q install ffmpeg libavcodec-extra
          python -m pip install --upgrade pip setuptools wheel
          pip install -q -r requirements_test.txt
          pip install -q -r <(sed '/^tensorflow/d;/^keras/d;/^tensorflow-addons/d;/^lingvo/d;/^Pillow/d' requirements_test.txt)
          pip install tensorflow==${{ matrix.tensorflow }}
          pip install keras==${{ matrix.keras }}
          pip install tensorflow-addons==${{ matrix.tf_addons }}
          pip install lingvo==0.13.1
          pip install Pillow==10.0.0
          pip list
      - name: Run ${{ matrix.name }} Tests
        run: pytest --cov-report=xml --cov=art --cov-append -q -vv tests/estimators/speech_recognition/test_tensorflow_lingvo.py --framework=${{ matrix.framework }} --durations=0
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
